

estadios = [
"Hailé Pinheiro (Serrinha)",
"Mangueirão",
"Heriberto Hülse",
"Couto Pereira",
"Rei Pelé",
"Independência",
"Fonte Luminosa",
"Raulino de Oliveira",
"Ressacada",
"Antônio Accioly",
"Arena da Baixada",
"Arena Pantanal",
"Arena Condá",
"Serra Dourada",
"Arena da Amazônia",
"Jorge Ismael de Biasi",
"Germano Krüger",
"Mangueirão",
"Independência",
"Arena Nicnet (Santa Cruz)",
"Arena Pantanal",
"Mangueirão",
"Ressacada",
"Couto Pereira",
"Hailé Pinheiro (Serrinha)",
"Heriberto Hülse",
"Rei Pelé",
"Arena Nicnet (Santa Cruz)",
"Fonte Luminosa",
"Independência",
"Germano Krüger",
"OBA",
"Arena Condá",
"Arena da Baixada",
"Independência",
"Arena da Amazônia",
"Jorge Ismael de Biasi",
"Mangueirão",
"Antônio Accioly",
"Raulino de Oliveira",
"Jorge Ismael de Biasi",
"Heriberto Hülse",
"OBA",
"Couto Pereira",
"Ressacada",
"Independência",
"Carlos Zamith",
"Mangueirão",
"Arena Pantanal",
"Arena Nicnet (Santa Cruz)",
"Fonte Luminosa",
"Mangueirão",
"Raulino de Oliveira",
"Antônio Accioly",
"Arena da Baixada",
"Arena Condá",
"Germano Krüger",
"Hailé Pinheiro (Serrinha)",
"Rei Pelé",
"Independência",
"Arena da Baixada",
"Ressacada",
"Hailé Pinheiro (Serrinha)",
"Heriberto Hülse",
"Arena Pantanal",
"Jorge Ismael de Biasi",
"Arena Nicnet (Santa Cruz)",
"Carlos Zamith",
"Mangueirão",
"Independência",
"Fonte Luminosa",
"Arena Condá",
"Couto Pereira",
"OBA",
"Independência",
"Antônio Accioly",
"Rei Pelé",
"Mangueirão",
"Raulino de Oliveira",
"Couto Pereira",
"Hailé Pinheiro (Serrinha)",
"Arena da Baixada",
"Mangueirão",
"Ressacada",
"Jorge Ismael de Biasi",
"Carlos Zamith",
"Heriberto Hülse",
"Arena Nicnet (Santa Cruz)",
"Arena Pantanal",
"Independência",
"Fonte Luminosa",
"OBA",
"Couto Pereira",
"Antônio Accioly",
"Independência",
"Germano Krüger",
"Rei Pelé",
"Raulino de Oliveira",
"Arena Condá",
"Curuzu",
"Arena Nicnet (Santa Cruz)",
"Jorge Ismael de Biasi",
"Arena Pantanal",
"Independência",
"Ressacada",
"Hailé Pinheiro (Serrinha)",
"Arena da Baixada",
"Mangueirão",
"Heriberto Hülse",
"Carlos Zamith",
"OBA",
"Curuzu",
"Rei Pelé",
"Arena da Baixada",
"Arena Sicredi",
"Antônio Accioly",
"Jorge Ismael de Biasi",
"Heriberto Hülse",
"Arena Condá",
"Raulino de Oliveira",
"Arena Nicnet (Santa Cruz)",
"Independência",
"Ressacada",
"Mangueirão",
"Jorge Ismael de Biasi",
"Couto Pereira",
"Antônio Accioly",
"Carlos Zamith",
"Germano Krüger",
"Hailé Pinheiro (Serrinha)",
"Rei Pelé",
"Heriberto Hülse",
"OBA",
"Arena da Baixada",
"Arena Sicredi",
"Raulino de Oliveira",
"Arena Condá",
"Jorge Ismael de Biasi",
"Curuzu",
"Arena Pantanal",
"Antônio Accioly",
"Couto Pereira",
"Mangueirão",
"Ressacada",
"Carlos Zamith",
"Fonte Luminosa",
"Arena Nicnet (Santa Cruz)",
"Germano Krüger",
"Independência",
"Hailé Pinheiro (Serrinha)",
"Rei Pelé",
"OBA",
"Jorge Ismael de Biasi",
"Curuzu",
"Arena da Baixada",
"Heriberto Hülse",
"Arena Condá",
"Arena Sicredi",
"Arena Nicnet (Santa Cruz)",
"Arena Pantanal",
"Germano Krüger",
"Mangueirão",
"Antônio Accioly",
"Fonte Luminosa",
"Hailé Pinheiro (Serrinha)",
"Couto Pereira",
"Ressacada",
"Raulino de Oliveira",
"Carlos Zamith",
"Independência",
"Germano Krüger",
"Arena da Baixada",
"Arena Sicredi",
"OBA",
"Arena Condá",
"Jorge Ismael de Biasi",
"Arena Pantanal",
"Carlos Zamith",
"Arena Nicnet (Santa Cruz)",
"Mangueirão",
"Fonte Luminosa",
"Rei Pelé",
"Couto Pereira",
"Raulino de Oliveira",
"Independência",
"Antônio Accioly",
"Ressacada",
"Curuzu",
"Heriberto Hülse",
"Hailé Pinheiro (Serrinha)",
"OBA",
"Mangueirão",
"Germano Krüger",
"Arena Nicnet (Santa Cruz)",
"Arena da Amazônia",
"Arena Condá",
"Jorge Ismael de Biasi",
"Arena da Baixada",
"Arena Sicredi",
"Arena Pantanal",
"Fonte Luminosa",
"Couto Pereira",
"Independência",
"Hailé Pinheiro (Serrinha)",
"Raulino de Oliveira",
"Ressacada",
"Antônio Accioly",
"Heriberto Hülse",
"Curuzu",
"Rei Pelé",
"Jorge Ismael de Biasi",
"Carlos Zamith",
"Mangueirão",
"OBA",
"Arena da Baixada",
"Arena Condá",
"Antônio Accioly",
"Raulino de Oliveira",
"Arena Sicredi",
"Germano Krüger",
"Arena Sicredi",
"Heriberto Hülse",
"Couto Pereira",
"Hailé Pinheiro (Serrinha)",
"Rei Pelé",
"Curuzu",
"Fonte Luminosa",
"Arena Pantanal",
"Arena Nicnet (Santa Cruz)",
"Ressacada",
"Mangueirão",
"Germano Krüger",
"Rei Pelé",
"Hailé Pinheiro (Serrinha)",
"Arena da Baixada",
"Antônio Accioly",
"Raulino de Oliveira",
"Arena Condá",
"Fonte Luminosa",
"Independência",
"Carlos Zamith",
"Mangueirão",
"Couto Pereira",
"Arena Nicnet (Santa Cruz)",
"Heriberto Hülse",
"Independência",
"Ressacada",
"Jorge Ismael de Biasi",
"Arena Pantanal",
"OBA",
"Raulino de Oliveira",
"Couto Pereira",
"Mangueirão",
"OBA",
"Germano Krüger",
"Arena Sicredi",
"Fonte Luminosa",
"Rei Pelé",
"Antônio Accioly",
"Arena Condá",
"Arena Nicnet (Santa Cruz)",
"Jorge Ismael de Biasi",
"Hailé Pinheiro (Serrinha)",
"Ressacada",
"Carlos Zamith",
"Baenão",
"Heriberto Hülse",
"Independência",
"Arena da Baixada",
"Arena Pantanal",
"Curuzu",
"Fonte Luminosa",
"OBA",
"Rei Pelé",
"Arena Sicredi",
"Germano Krüger",
"Raulino de Oliveira",
"Couto Pereira",
"Antônio Accioly",
"Arena Condá",
"Arena da Baixada",
"Heriberto Hülse",
"Jorge Ismael de Biasi",
"Mangueirão",
"Arena Nicnet (Santa Cruz)",
"Arena Pantanal",
"Carlos Zamith",
"Independência",
"Ressacada",
"Hailé Pinheiro (Serrinha)",
"Curuzu",
"OBA",
"Arena Sicredi",
"Couto Pereira",
"Rei Pelé",
"Arena Condá",
"Raulino de Oliveira",
"Fonte Luminosa",
"Germano Krüger",
"Antônio Accioly",
"Carlos Zamith",
"Hailé Pinheiro (Serrinha)",
"Arena Nicnet (Santa Cruz)",
"Arena Pantanal",
"Germano Krüger",
"Ressacada",
"Independência",
"Fonte Luminosa",
"Couto Pereira",
"Baenão",
"Arena Sicredi",
"Jorge Ismael de Biasi",
"OBA",
"Heriberto Hülse",
"Arena Pantanal",
"Raulino de Oliveira",
"Rei Pelé",
"Mangueirão",
"Arena Condá",
"Arena da Baixada",
"Carlos Zamith",
"Antônio Accioly",
"Independência",
"Baenão",
"Ressacada",
"Germano Krüger",
"Couto Pereira",
"Arena Nicnet (Santa Cruz)",
"Hailé Pinheiro (Serrinha)",
"Fonte Luminosa",
"Jorge Ismael de Biasi",
"Arena Pantanal",
"Arena Sicredi",
"Raulino de Oliveira",
"Curuzu",
"Heriberto Hülse",
"Rei Pelé",
"OBA",
"Arena Condá",
"Arena da Baixada",
"Couto Pereira",
"Antônio Accioly",
"Fonte Luminosa",
"Hailé Pinheiro (Serrinha)",
"Ressacada",
"Carlos Zamith",
"Baenão",
"Germano Krüger",
"Independência",
"Raulino de Oliveira",
"Arena Sicredi",
"Arena Pantanal",
"Jorge Ismael de Biasi",
"Arena da Baixada",
"OBA",
"Heriberto Hülse",
"Rei Pelé",
"Curuzu",
"Arena Condá",
"Arena Nicnet (Santa Cruz)",
"Curuzu",
"Couto Pereira",
"Antônio Accioly",
"Ressacada",
"Rei Pelé",
"Raulino de Oliveira",
"Hailé Pinheiro (Serrinha)",
"Heriberto Hülse",
"Independência",
"Fonte Luminosa",
"OBA",
"Jorge Ismael de Biasi",
"Arena da Baixada",
"Arena Pantanal",
"Mangueirão",
"Arena Condá",
"Germano Krüger",
"Carlos Zamith",
"Arena Sicredi",
"Arena Nicnet (Santa Cruz)"
]

# Remove duplicatas usando set e mantém a ordem
estadios_unicos = list(dict.fromkeys(estadios))  # Dict mantém ordem desde o Python 3.7

print("Lista de estádios sem duplicatas serie B 2025:")
# Ordena a lista em ordem alfabética
estadios_ordenados = sorted(estadios_unicos)  # Cria uma nova lista ordenada

print("Lista de estádios sem duplicatas e em ordem alfabética:")
print(f"Quatidade de estádio: {len(set(estadios_ordenados))}")
print(estadios_ordenados)
# Lista de estádios sem duplicatas serie B 2025:
# ['Antônio Accioly', 'Arena Condá', 'Arena Nicnet (Santa Cruz)', 'Arena Pantanal', 'Arena Sicredi', 'Arena da Amazônia', 'Arena da Baixada', 'Baenão', 'Carlos Zamith', 'Couto Pereira', 'Curuzu', 'Fonte Luminosa', 'Germano Krüger', 'Hailé Pinheiro (Serrinha)', 'Heriberto Hülse', 'Independência', 'Jorge Ismael de Biasi', 'Mangueirão', 'OBA', 'Raulino de Oliveira', 'Rei Pelé', 'Ressacada', 'Serra Dourada']

